namespace Past.Protocol.Enums
{
    public enum StatEnum
    {
        HEALTH,
        INITIATIVE,
        PROSPECTING,
        ACTION_POINTS,
        MOVEMENT_POINTS,
        STRENGTH,
        VITALITY,
        WISDOM,
        CHANCE,
        AGILITY,
        INTELLIGENCE,
        RANGE,
        SUMMONABLE_CREATURES_BOOST,
        REFLECT,
        CRITICAL_HIT,
        CRITICAL_MISS,
        HEAL_BONUS,
        ALL_DAMAGES_BONUS,
        WEAPON_DAMAGES_BONUS_PERCENT,
        DAMAGES_BONUS_PERCENT,
        TRAP_BONUS,
        TRAP_BONUS_PERCENT,
        PERMANENT_DAMAGE_PERCENT,
        DODGE_PA_LOST_PROBABILITY,
        DODGE_PM_LOST_PROBABILITY,
        NEUTRAL_ELEMENT_RESIST_PERCENT,
        EARTH_ELEMENT_RESIST_PERCENT,
        WATER_ELEMENT_RESIST_PERCENT,
        AIR_ELEMENT_RESIST_PERCENT,
        FIRE_ELEMENT_RESIST_PERCENT,
        NEUTRAL_ELEMENT_REDUCTION,
        EARTH_ELEMENT_REDUCTION,
        WATER_ELEMENT_REDUCTION,
        AIR_ELEMENT_REDUCTION,
        FIRE_ELEMENT_REDUCTION,
        PVP_NEUTRAL_ELEMENT_RESIST_PERCENT,
        PVP_EARTH_ELEMENT_RESIST_PERCENT,
        PVP_WATER_ELEMENT_RESIST_PERCENT,
        PVP_AIR_ELEMENT_RESIST_PERCENT,
        PVP_FIRE_ELEMENT_RESIST_PERCENT,
        PVP_NEUTRAL_ELEMENT_REDUCTION,
        PVP_EARTH_ELEMENT_REDUCTION,
        PVP_WATER_ELEMENT_REDUCTION,
        PVP_AIR_ELEMENT_REDUCTION,
        PVP_FIRE_ELEMENT_REDUCTION
    }

    public enum StatBoost : sbyte
    {
        STRENGTH = 10,
        VITALITY = 11,
        WISDOM = 12,
        CHANCE = 13,
        AGILITY = 14,
        INTELLIGENCE = 15
    }
}
